### ISSUE TITLE
Can't launch the jar file

### ISSUE THREAD

**Issue by johnstonian** [tofi86/Jarbundler#2]
I'm new to this project. How to I run this program? I'm using running Mac on 10.10.5 (Yosemite).

I downloaded and installed ant and the appbundler (https://java.net/projects/appbundler/downloads) and placed them in /usr/share/java/ant as other sites suggested.

Not sure what step I am missing here. When I open jarbundler-2.4.0.jar I get an error that the Java JAR file could not be launched. Image attached of the error.

What am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/2810863/11002558/1710c5fc-8473-11e5-833f-301434b6459e.png)

**Comment by tofi86** [comment]
What do you want to achive by running the jar file? What do you think should it do?

If you already use appbundler, why would you use this JarBundler library as well?

Both libraries are meant to be used in an ANT build script. Not at the same time, for sure, but either one of them...

For further questions please read the manual. You can download it with the release zip file: https://github.com/tofi86/Jarbundler/releases

**Comment by johnstonian** [comment]
sorry, i didn't mean to post this as a bug or issue. 

Once I copy the jarbundler into my ant library, how do i run the ant builder?

do i type in 'ant' into the project directory (with a build.xml file) that i want to build?

**Comment by tofi86** [comment]
Sorry, I cannot provide basic ant support. You need to know how to write and launch an ant file.

I for example, always run the ant `build.xml` files from within eclipse.

If you don't know how to set up your JarBundler ant task, please read the documentation (e.g. `dox/index.html` if you downloaded the package).

This is a complex example from one of my apps:

```
    <taskdef name="jarbundler"
        classname="net.sourceforge.jarbundler.JarBundler"
        classpath="${antLib.dir}/jarbundler/jarbundler.jar" />

    <jarbundler
        dir="${out.dir}"
        name="EPUB-Checker"
        shortname="pagina EPUB-Checker"
        bundleid="de.paginagmbh.epubchecker"
        mainclass="de.paginagmbh.epubchecker.paginaEPUBChecker"
        stubfile="${build.dir}/MacJavaStub/universalJavaApplicationStub"
        usejavaxkey="true"
        icon="${build.dir}/icons/paginaEPUBChecker_1024.icns"
        splashfile="SplashScreen_Mac.png"
        version="${program.version.txtNumber}"
        developmentregion="German"
        allowMixedLocalizations="true"
        signature="PAEC"
        build="${program.version.build}"
        copyright="© 2010-${YEAR} pagina GmbH, Tübingen, Germany"
        jvmversion="1.7+">

        <!-- this documenttype lets me received drag/drop events from safari to my dock icon -->
        <!-- http://informagen.com/JarBundler/DocumentType.html -->
        <documenttype
            name="EPUB files"
            extensions="epub EPUB"
            role="Viewer"/>

        <jarfileset dir="${out.dir}">
            <include name="paginaEPUBChecker.jar" />
        </jarfileset>

        <resourcefileset dir="${build.dir}/splashscreen/">
            <include name="SplashScreen_Mac.png"/>
        </resourcefileset>

    </jarbundler>
```

**Comment by johnstonian** [comment]
thank you, that is helpful. I do think it is something with JarBundler ant task I am trying to make.

I have the following task definition in my build.xml file:

`<taskdef name="jarbundler"
             classname="net.sourceforge.jarbundler.JarBundler"
             classpath="${antLib.dir}/lib/jarbundler-2.5.0.jar" />`

when I run the ant task, the following error is thrown:

`taskdef class net.sourceforge.jarbundler.JarBundler cannot be found
 using the classloader AntClassLoader[]`

Do I need to include more than just the jarbundler.jar file in my ant library folder?

**Comment by johnstonian** [comment]
nevermind. i'm dumb. had to add the jarbundler.jar inside my homebrew install of ant.

thank you for your patience :)
