### ISSUE TITLE
Your Readme is a bit outdated

### ISSUE THREAD

**Issue by Vampire** [tofi86/Jarbundler#4]
Hey there, the official JarBundler is now also at GitHub under https://github.com/UltraMixer/JarBundler and also has the JavaX possibility.
And as soon as my PR https://github.com/UltraMixer/JarBundler/pull/8 is hopefully accepted, it also supports the Oracle PList format if JVM Version is at least 1.7. :-)

**Comment by tofi86** [comment]
Yeah, I know about that as I'm also a contributor/maintainer of [UltraMixer/JarBundler](https://github.com/UltraMixer/JarBundler/)

Unfortunately I haven't had very much time lately to maintain this project...
Will change the readme soon...

**Comment by tofi86** [comment]
The Readme of [tofi86/universalJavaApplicationStub](https://github.com/tofi86/universalJavaApplicationStub) has also [been changed](https://github.com/tofi86/universalJavaApplicationStub/commit/76222cd01e1e2d301956de66dc248753bc36167e) to reflect these changes...

**Comment by Vampire** [comment]
If you are a maintainer for the UltraMixer JarBundler, how about accepting my pull request then? :-)
